# Generated by Django 4.2.18 on 2025-03-18 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booth',
            name='unique_id',
        ),
        migrations.AddField(
            model_name='booth',
            name='years',
            field=models.IntegerField(default=0),
        ),
    ]