# Generated by Django 4.2.18 on 2025-03-18 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_circle'),
    ]

    operations = [
        migrations.AddField(
            model_name='booth',
            name='circle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='map.circle'),
        ),
    ]
