# Generated by Django 4.2.18 on 2025-03-19 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0004_booth_circle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booth',
            old_name='years',
            new_name='year',
        ),
    ]
