# Generated by Django 4.2.18 on 2025-03-22 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0006_category_alter_circle_name_circle_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='test_image',
            field=models.ImageField(blank=True, null=True, upload_to='map/test_images', verbose_name='テスト画像'),
        ),
    ]