# Generated by Django 4.2.18 on 2025-03-23 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0007_room_test_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booth',
            name='name',
        ),
    ]