# Generated by Django 4.2.18 on 2025-03-27 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0009_remove_booth_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Connector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, null=True)),
                ('test_image', models.ImageField(blank=True, null=True, upload_to='map/test_images', verbose_name='チE��ト画僁E)),
            ],
        ),
        migrations.AddField(
            model_name='floor',
            name='connector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='map.connector'),
        ),
    ]