# Generated by Django 4.2.18 on 2025-03-27 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0010_connector_floor_connector'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='floor',
            name='connector',
        ),
        migrations.AddField(
            model_name='connector',
            name='Floor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='map.floor'),
        ),
    ]