# Generated by Django 4.2.18 on 2025-03-28 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0013_rename_floor_connector_floor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connector',
            name='test_image',
            field=models.ImageField(blank=True, null=True, upload_to='map/test_images', verbose_name='チャット画像'),
        ),
        migrations.AlterField(
            model_name='room',
            name='test_image',
            field=models.ImageField(blank=True, null=True, upload_to='map/test_images', verbose_name='チャット画像'),
        ),
    ]
