# Generated by Django 4.2.18 on 2025-04-01 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0014_alter_connector_test_image_alter_room_test_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='floor',
            name='svg_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
